face_detection/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from face_detection import views as app_views
app_name='faceRecog'
urlpatterns = [
    #url(r'^$', app_views.index),
    #url(r'^error_image$', app_views.errorImg),
    url(r'^create_dataset$', app_views.create_dataset,name='data'),
    #url(r'^trainer$', app_views.trainer),
    url(r'^detect$', app_views.detect,name="detect"),
    #url(r'^detect_image$', app_views.detectImage),
    url(r'^admin/', admin.site.urls)
]

poll/fusioncharts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import catalogue

from .samples import simple, static_json_example, static_xml_example, dict_json_example, dict_xml_example 
from .samples import annotation_example, fusion_maps, gantt_chart_example, angular_gauge_example
from .samples import linked_chart_single_level, single_series_chart, multi_series_chart, xy_chart
from .samples import column2d_database, database_example, database_drilldown_example
from .samples import a_3d_pie_chart, a_column_line_area_combi_chart
from .samples import fetching_data_from_json_url, fetching_data_from_xml_url, mul_col2d_using_dict
from .samples import client_side_chart_export, render_angular_and_gauge, render_pyramid_and_funnel_charts

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', catalogue),
    url(r'^simple/', simple.chart, name='chart'),
    url(r'^static-json-example/', static_json_example.chart, name='chart'),
    url(r'^static-xml-example/', static_xml_example.chart, name='chart'),
    url(r'^dict-json-example/', dict_json_example.chart, name='chart'),
    url(r'^dict-xml-example/', dict_xml_example.chart, name='chart'),
    url(r'^annotation-example/', annotation_example.chart, name='chart'),
    url(r'^map-example/', fusion_maps.chart, name='chart'),
    url(r'^gantt-chart-example/', gantt_chart_example.chart, name='chart'),
    url(r'^angular-gauge-example/', angular_gauge_example.chart, name='chart'),
    url(r'^linked-chart-single-level-example/', linked_chart_single_level.chart, name='chart'),
    url(r'^single-series-chart-example/', single_series_chart.chart, name='chart'),
    url(r'^multi-series-chart-example/', multi_series_chart.chart, name='chart'),
    url(r'^xy-chart-example/', xy_chart.chart, name='chart'),
    url(r'^database-example/', database_example.chart, name='chart'),
    url(r'^database-drilldown-example/', database_drilldown_example.chart, name='chart'),
    url(r'^render-3d-pie-chart/', a_3d_pie_chart.chart, name='chart'),
    url(r'^render-column-line-area-combi-chart/', a_column_line_area_combi_chart.chart, name='chart'),
    url(r'^fetching-data-from-json-url/', fetching_data_from_json_url.chart, name='chart'),
    url(r'^fetching-data-from-xml-url/', fetching_data_from_xml_url.chart, name='chart'),
    url(r'^client-side-chart-export/', client_side_chart_export.chart, name='chart'),
    url(r'^render-angular-and-gauge/', render_angular_and_gauge.chart, name='chart'),
    url(r'^render-pyramid-and-funnel-charts/', render_pyramid_and_funnel_charts.chart, name='chart'),
    url(r'^mul-col2d-using-dict/', mul_col2d_using_dict.chart, name='chart'),
    url(r'^render-column-2d-using-database/', column2d_database.chart, name='chart')
]

poll/urls.py
from django.urls import path, include
from poll.views import *
app_name='poll'
urlpatterns=[path('',IndexView.as_view(),name='index'),
path('login/',LoginView.as_view(),name='login'),
path('home',RegisterElecteur.as_view(),name='regVoter'),
path('logout',LogoutView.as_view(),name='logout'),
path('admin',AdPicture,name='ap'),
path('home/register agents/',RegAgents.as_view(),name='regAgents'),
path('regparty',RegParty.as_view(),name='regParty'),
path('home/save party/',SaveParty.as_view(),name="saveParty"),
path('home/register candidate',RegCandidates.as_view(),name='regCand'),
path('home/save candidate',SaveCandidates.as_view(),name='saveCand'),
path('vote/',Votes.as_view(),name="vote"),
path('home/password/',PassWord.as_view(),name="pw"),
path('change/',Change_password.as_view(),name='chPW'),
path('home/result',test,name='chart')
]

pollOneline2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/',include('poll.urls')),
    path('face/',include('face_detection.urls')),
]
#urlpatterns += patterns('django.views.static',(r'^ml/dataset/(?P<path>.*)','serve',{'document_root':settings.MEDIA_ROOT}), )

poll/fusioncharts/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.
class Revenue(models.Model):
	MonthlyRevenue = models.CharField(max_length=50)
	Month = models.CharField(max_length=50)

	def __unicode__(self):
		return u'%s %s' % (self.MonthlyRevenue, self.Month)

class City(models.Model):
	Name = models.CharField(max_length=50)
	CountryCode = models.CharField(max_length=50)
	Population = models.CharField(max_length=50)

	def __unicode__(self):
		return u'%s %s %s' % (self.Name, self.CountryCode, self.Population)

class Country(models.Model):
	Name = models.CharField(max_length=50)
	Code = models.CharField(max_length=50)
	Population = models.CharField(max_length=50)

	def __unicode__(self):
		return u'%s %s %s' % (self.Name, self.Code, self.Population)
						

poll/models.py
from django.db import models
from django.db.models.signals import post_save
from django import forms
from django.dispatch import receiver
from django.contrib.auth.models import User
#all our voters and administrators will be managed in the same table
class Electeur(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    #cni_number=models.IntegerField(primary_key=True)
    #here the cni_number will be used for username to 
    # help identify the user uniquely
    date_of_birth=models.DateField(null=True)
    palce_of_birth=models.CharField(max_length=15)
    picture=models.ImageField(upload_to="faces/")
    level=[("Agent","Agent"),("President","Surpeme court présidents"),("Voter","voter")]
    status=models.CharField(max_length=12,choices=level,default="Voter")
#the methods below specify that each time a new user is created,
#a voter(electeur) profile is assigned to him
@receiver(post_save,sender=User)
def create_electeur_profile(sender,instance,created, **kwargs):
    if created:
        Electeur.objects.create(user=instance)
@receiver(post_save,sender=User)
def save_electeur_profile(sender,instance,**kwargs):
    instance.electeur.save()

class Party(models.Model):
    p_name=models.CharField(max_length=45)
    p_acronyme=models.CharField(max_length=5)
    p_logo=models.ImageField(upload_to='logos/')

class Candidate(models.Model):
    nom=models.CharField(max_length=25)
    prenom=models.CharField(max_length=25)
    party=models.ForeignKey(Party,on_delete=models.CASCADE)

class Vote(models.Model):
    voter=models.ForeignKey(Electeur,on_delete=models.CASCADE)
    p_party=models.ForeignKey(Party,on_delete=models.CASCADE)

poll/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *
class RegistrationForm(UserCreationForm):
    date_of_birth=forms.DateField(label='dob',help_text='required Format:YY-M-D')
    place_of_birth=forms.CharField(label='pob')
    class Meta:
        model=User
        fields=('first_name','last_name','date_of_birth','place_of_birth','username')

class CandidateForm(forms.Form):

    class Meta:
        model=Candidate
        fields=('nom','prenom','party')

class Vote(forms.Form):
    class Meta:
        model=Vote
        fields=('voter','party')

poll/fusioncharts/views.py
from django.shortcuts import render

# it is a default view.
# please go to the samples folder for others view

def catalogue(request):
 	return  render(request, 'catalogue.html')

poll/views.py
from django.shortcuts import render, redirect
import json
import random
from highcharts.views import HighChartsBarView
from django.db.models import Count, Q
from django.contrib.auth.hashers import make_password,check_password
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.views import View
from django.contrib.auth import authenticate, login,urls, logout
from .forms import *
from .fusioncharts.fusioncharts import FusionCharts
import os
from face_detection.views import detect
from poll.models import *
# Create your views here.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
import datetime, time

#------*---*-- Take note of the line below
#eldate=datetime.date(2018,11,11)
#------*--*--- to set the current as the election day,uncomment the line below and comment the one up
eldate=datetime.date.today()

class IndexView(View):
    """vue présentant la page d'acceuil site de vote"""
    def get(self,request):
        party=Party.objects.order_by('pk')
        context={'party':party}
        return render(request,'poll/index.html',context)

def AdPicture(request):
    """requis pour ajouter la photo dun utilisateur au profil actuel"""
    userId=request.session['userId']
    request.session['userId']
    request.session['userId']=userId
    picture=BASE_DIR+'/ml/dataset/'+str(id)+'.'+str(1)+'.jpg'
    request.session['picture']=picture
    context={'picture':picture,'form':RegistrationForm()}
    return render(request,'poll/homeAdmin1.html',context)

class LoginView(View):
    """this view checks user informations and sends the user to the 
    appropriate destination according to the current date"""
    def post(self,request):
        username=request.POST['nom']
        password=request.POST['pw']
        user=authenticate(request,username=username,password=password)
        if user is not None:
            if eldate==datetime.date.today():
                if user.electeur in [p.voter for p in Vote.objects.all()]:
                    login(request,user)
                    return redirect('poll:chart')
                else:
                    face=detect(request,user.username)
                    #time.sleep(10)
                    if face:
                        party=Party.objects.order_by('pk')
                        context={'party':party}
                        login(request,user)
                        return render(request,'poll/vote.html',context)
                    else:
                        return redirect('poll:index')
            else:
                """each user should be sent to the appropriate direction"""
                if user.electeur.status=="Agent":
                    """the agents"""
                    form=RegistrationForm()
                    login(request,user)
                    return render(request,'poll/homeAdmin1.html')
                elif user.electeur.status=="President":
                    """the president of the supreme court"""
                    login(request,user)
                    return render(request,'poll/superAdmin.html',{'form':RegistrationForm()})
                else:
                    """the voters"""
                    login(request,user)
                    return render(request,'poll/homeVoter.html')
                    
        else:
            """the user is not defined"""
            return redirect('poll:index')

class LogoutView(View):
    def get(self,request):
        logout(request)
        return redirect('poll:index')
 
class RegisterElecteur(View):
    """called to save the Voter"""
    def post(self,request):
        satut=''
        """here we should know the tipe of user we are saving"""
        if request.user.electeur.status=="Agent":
            satut="Voter"
        else:
            satut="Agent"
        try:
            u=str(request.session['userId'])
            name=request.POST['name']
            surname=request.POST['surname']
            dob=request.POST['dob']
            pob=request.POST['pob']
            us=User.objects.create(username=u,first_name=name,last_name=surname,password=make_password(u))
            el=Electeur.objects.get(user=us)
            el.date_of_birth=dob
            el.place_of_birth=pob
            el.status=satut
            #us.electeur.picture=BASE_DIR+'ml/dataset'+u+".1.jpg"
            el.save()
            return render(request,'poll/homeAdmin1.html')
        except:
           return render(request,'poll/homeAdmin1.html',{'error':"Error, fill the form and try again"})
            

class RegAgents(View):
    def get(self,request):

        return render(request,'poll/regAgents.html')

class SaveParty(View):
    """cette vue enregistre les parties politiques dans la base de données"""
    def post(self,request):
        pname=request.POST['party']
        pacronyme=request.POST['acronym']
        logo=request.POST['logo']
        party=Party(p_name=pname,p_acronyme=pacronyme,p_logo=logo)
        party.save()
        return render(request,'poll/superAdmin.html')

class RegParty(View):
    """vue chargée de retourner la page d'enregistrement des parties politiques"""
    def get(self,request):
        return render(request,'poll/regParty.html')
class RegCandidates(View):
    def get(self,request):
        party=Party.objects.order_by('pk')
        context={'party':party}
        return render(request,'poll/regCandidates.html',context)

class SaveCandidates(View):
    """cette vue enregistre les parties politiques dans la base de données"""
    def post(self,request):
        name=request.POST['nom']
        sname=request.POST['surname']
        pname=request.POST['party']
        party=Party.objects.get(p_acronyme=pname)
        candidate=Candidate(nom=name,prenom=sname,party=party)
        candidate.save()
        return render(request,'poll/superAdmin.html')

class Votes(View):
    def post(self,request):
        electeur=request.user
        choix=request.POST['party']
        party=Party.objects.get(p_acronyme=choix)
        vote=Vote(voter=electeur.electeur,p_party=party)
        vote.save()
        return redirect('poll:index')

class Change_password(View):
    def post(self,request):
        ppw=request.POST['prev']
        npw=request.POST['new']
        if request.user.check_password(ppw):
            if len(str(npw))<8:
                err="Your password should be at least 8 characters long"
                return render(request,'poll/changePassword.html',{'error':err})
            else:
                request.user.set_password(npw)
                request.user.save()
                return redirect('poll:logout')
        else:
            err="The previous password didn't match, try again"
            return render(request,'poll/changePassword.html',{'error':err})

class PassWord(View):
    def get(selt,request):
        return render(request,'poll/changePassword.html')

class Result(HighChartsBarView):
    categories=list()
    for p in Party.objects.all():
        categories.append(p.p_acronyme)
    @property
    def series(self):
        result=list()
        for name in ('joe','jack','William','averell'):
            data=list()
            for x in range(len(self.categories)):
                data.append(random.randint(0,10))
            result.append({'name':name,"data":data})
        return render('poll/chart.html',{'result':json.dumps(result)})
"""def chart(request):
    dataset=list()
    abst=Vote.objects.count()
    for p in Party.objects.all():
        d=dict()
        d['party']=p.p_acronyme
        c=0
        for v in Vote.objects.all():
           if v.p_party is p:
               c+=1
        d['v']=(c/abst)*100
        dataset.append(d)
    parties=list()
    voix=list()
    for entry in dataset:
        parties.append(entry['party'])
        voix.append(entry['v'])
    return render (request,'poll/chart.html',
    {'categories':json.dumps(parties),
    'voix':json.dumps(voix)})"""

def test(request):
    return render(request,'poll/chart.html')

poll/templates/poll/changePassword.html
{%extends 'poll/homebase.html'%}
{%block title%}
    Change your password
    {%block content%}
    {%load static%}
    <div class="top-content" style="background-image:url({% static 'poll/img/backgrounds/7.jpg' %});">   
            <div class="container">
                <div class="row">
                    <div class="col-sm-5 text">
                        <h1><strong>ELECAM</strong> Registration Campaign</h1>
                        <div class="description">
                            <p>
                                By default, your password was the same as your user name that is your ID card number 
                                you can change this here. For more iformation go to <a href="http://elecam.gov"><strong>ELECAM</strong></a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-5 form-box">
                        <div class="form-top" style="margin-top:0%;">
                            <div class="form-top-left">
                            {%if error%}
                            <h2 class="er"><i>{{error}}</i></h3>
                            {%else%}
                                <h3>PASWORD</h3>
                            {%endif%}
                            </div>
                        </div>
                        <div class="form">
                            <form role="form" action="{%url 'poll:chPW'%}" method="post" class="registration-form">
                                {%csrf_token%}
                                <fieldset>
                                    <div class="form-group">
                                        <label class="sr-only" for="form-dob">Email</label>
                                        <input type="text" name="prev" placeholder="Actual password" class="form-date form-control" id="form-date">
                                    </div>
                                    <div class="form-group">
                                         <label class="sr-only" for="form-pob">Last name</label>
                                         <input type="text" name="new" placeholder="New Password" class="form-pob form-control" id="form-pob">
                                     </div>
                                
                                    <div class="form-group">
                                    <button type="submit" class="btn">Sign me up!</button>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    {%endblock%}
{%endblock%}

poll/templates/poll/homeVoter.html
{% extends "poll/homebase.html" %}
{%block title%}Welcome{% endblock %}
{%block addload%}
    {%load static%}
    <script src="{% static '/poll/Highcharts-6.1.0/code/js/highcharts.src.js' %}"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/data.js"></script>
    <script src="https://code.highcharts.com/modules/drilldown.js"></script>
    
 
    <link rel="stylesheet" href="{% static 'poll/css/style1.css' %}">
    {%endblock%}
{%block content%}
{%load static%}
<div class="top-content" style="background-image:url({% static 'poll/img/backgrounds/7.jpg' %});">

        <div class="inner-bg">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 text">
                        <h1 class="wow fadeInLeftBig" data-wow-duration="1.5s" data-wow-delay="1s">
                            2018 Election <strong>Coming Soon</strong>
                        </h1>
                        <div class="description wow fadeInLeftBig" data-wow-duration="1.5s" data-wow-delay="2s">
                            <p>
                                Befor the Election day, this plaform is only acessible by the ELECAM registration agents
                                and the President of the supreme cout. You are advised to <a href="{% url 'poll:pw' %}"><strong style="color: red;">your password</strong></a> for secutity 
                                purpose
                            </p>
                        </div>
                        <div class="timer wow fadeInUp">
                            <p id="demo" class="timer" style="color:red;"></p>
                        </div>

    <script>
    // Set the date we're counting down to
    var countDownDate = new Date("Oct 11, 2018 00:00:00").getTime();

    // Update the count down every 1 second
    var x = setInterval(function() {

        // Get todays date and time
        var now = new Date().getTime();
        
        // Find the distance between now an the count down date
        var distance = countDownDate - now;
        
        // Time calculations for days, hours, minutes and seconds
        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);

        //Output the result in an element with id="demo"
        document.getElementById("demo").innerHTML = days + "days " + hours + "h "
        + minutes + "min" + seconds + "sec ";
        
        // If the count down is over, write some text 
        if (distance < 0) {
            clearInterval(x);
            document.getElementById("demo").innerHTML = "EXPIRED";
        }
    }, 1000);
    </script>
                    </div>
                </div>
            </div>
        </div> 
</div>
{%endblock%}
<!-- Javascript -->
{%load static%}
<script src="{% static 'poll/js/jquery-1.11.1.min.js'%}"></script>
<script src="{% static 'poll/bootstrap/js/bootstrap.min.js'%}"></script>
<script src="{% static 'poll/js/jquery.backstretch.min.js'%}"></script>
<script src="{% static 'poll/js/jquery.countdown.min.js'%}"></script>
<script src="{% static 'poll/js/wow.min.js'%}"></script>
<script src="{% static 'poll/js/retina-1.1.0.min.js'%}"></script>
<script src="{% static 'poll/js/scripts.js'%}"></script>

poll/templates/poll/modal.html
		<!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">Input unique id and wait for webcam</h4>
                </div>
                <div class="modal-body">
                  <ul>
                    <li>For higher accuracy, make sure to stay in room with good lightning.</li>
                    <li>Please remove any type of accesories from face.</li>
                    <li>Make sure your face in clearly visible in camera.</li>
                    <li>Make sure your hair is not blocking the face.</li>
                    <li>Make sure no other faces are within the cam frame.
                  </ul>
                  <hr/>
                  <form action="{%url 'faceRecog:data'%}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                      <label for="inputId">Renter Unique ID*</label>
                      <input type="text" class="form-control" name="userId" id="inputId" placeholder="CNI_number">
                    </div>
                    <button type="submit" class="btn btn-warning">Submit</button>
                  </form>
                </div>
              </div>
            </div>
          </div>

poll/templates/poll/modal1.html
<div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-sm">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 style="color:red;" class="h4_login"><span class="glyphicon glyphicon-lock"></span> Login</h4>
                </div>
                <div class="modal-body">
                    <form role="form" method="POST" action="{%url 'poll:login'%}">
                        {%csrf_token%}
                        <div class="form-group">
                          <h6 style="font-style: italic;font-size: 10px;color: red;">{{message|lower}}</h6>
                        </div>
                        <div class="form-group">
                          <label for="usrname"><span class="glyphicon glyphicon-user"></span> Username</label>
                          <input type="text" class="form-control" id="usrname" name="nom" placeholder="Enter CNI numner" required/>
                        </div>
                        <div class="form-group">
                          <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Password</label>
                          <input type="password" class="form-control" id="psw" name="pw" placeholder="Enter password" required/>
                        </div>
                        
                        
                                                    
                        <!-- captcha codes
                        <form action="" method="post" name="form1" id="form1" > -->
                        <!-- <div class="form-group">
                            <table width="270" border="0" align="center" cellpadding="5" cellspacing="2" class="tables">
                                <?php if(isset($msg)){?>
                                
                                <tr>
                                  <td colspan="2" align="center" valign="top" ><div class="alert alert-danger"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><?php echo $msg?></div></td>
                                </tr>
                                <?php } ?>
                                <tr>
                                  
                                  <td align="center"><img src="resources/captcha/captcha.php?rand=<?php echo rand();?>" id='captchaimg'></img><br/>
                                    
                                    <label for='message'><span class="glyphicon glyphicon-qrcode"></span> Enter the code above here :</label>
                                    <input id="captcha_code" name="captcha_code" type="text" class="form-control" placeholder="Enter code here"required /><br/>
                                    <label for='message'><span class="glyphicon glyphicon-eye-close"></span> 
                                    Can't read the image? click <a href="javascript: refreshCaptcha();" class="refresh"><span class="glyphicon glyphicon-refresh"></span></a> to refresh.</label>
                                 </td>
                                </tr>
                            </table>
                        </div>
                        
                        -->
                        
                        <div class="checkbox">
                          <label><input type="checkbox" value="" checked>Remember me</label>
                        </div>
                        <button type="submit" name="Submit" class="btn btn-default btn-success btn-block"><span class="glyphicon glyphicon-off"></span> Login</button>
                      
                    </form>
                </div>
                <div class="modal-footer">
                  <button type="submit" class="btn btn-default btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
                  <p>Forgot <a href="#" class="forgot_password">Password?</a></p>
                </div>
            </div>
        </div>
    </div>

poll/templates/poll/services.html
<div id="bottom_rows">
        <div class="row">
            <div class="col-md-3">
            <h4 id="title_services">complains</h4>
            <p class="services" style="text-align:left">For any fraud or any complain , please contact ...<br/> (+237) 672915012, (+237) 691297336, <br/>(+237) 693775081</p>
            </div>
            <div class="col-md-3">
                <h4 id="title_services">Political parties</h4>
                <ul class="services" style="text-align:left">
                    {%for p in party%}
                        <li><a href="#">{{p.p_acronyme}}</a></li>
                    {%endfor%}
                </ul>
            </div>
            <div class="col-md-3" style="text-align:left">
                <h4 id="title_services">Campain polices</h4>
                <ul class="services">
                    <li><a href="#">Lorem ipsum</a></li>
                    <li><a href="#">Lorem ipsum</a></li>
                    <li><a href="#">Lorem ipsum</a></li>
                </ul>
            </div>
            <div class="col-md-3">
                        
            </div>
        </div>
    </div>

poll/templates/poll/superAdmin.html
{% extends "poll/homebase.html" %}
{% block title %}Super Admin{% endblock %}
{% block content %}

	<ul class="nav nav-tabs">
		<li class="active"><a href="#">Home</a></li>
		<li><a href="{%url 'poll:regAgents'%}">Register Agents</a></li>
		<li><a href="{%url 'poll:regParty'%}">Register Political Parties</a></li>
		<li><a href="{%url 'poll:regCand'%}">Register Candidates</a></li>
		<!--<li><a href="#">Set Elections date</a></li>-->
		<!--<li><a href="#">Set campagain date</a></li>-->
	</ul>
	  {%load static%}
	
		<div class="top-content" style="background-image:url({% static 'poll/img/backgrounds/7.jpg' %});">
        	{%block admcontent%}
            <div class="inner-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-7 text">
                            <h1><strong>ELECAM</strong> Registration Campaign</h1>
                            <div class="description">
                            	<p>
	                            	This is a platform is for the President of supreme court only for more go to <a href="http://elecam.gov"><strong>ELECAM</strong></a>
                            	</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
			{%endblock%}
		</div>
{% endblock %}